export const chartColorsData = [
    {
        groupName: "Charts / Primary",
        tokens: [
            { name: "cm.sys.color.charts.primary-outline", lightValue: "#1a73e8", darkValue: "#8ab4f8" },
            { name: "cm.sys.color.charts.primary-default", lightValue: "#1a73e8", darkValue: "#8ab4f8" },
            { name: "cm.sys.color.charts.primary-medium", lightValue: "#8ab4f8", darkValue: "#4285f4" },
            { name: "cm.sys.color.charts.primary-low", lightValue: "#d2e3fc", darkValue: "#333E50" },
        ]
    },
    {
        groupName: "Charts / Neutral",
        tokens: [
            { name: "cm.sys.color.charts.neutral-outline", lightValue: "#80868b", darkValue: "#dadce0" },
            { name: "cm.sys.color.charts.neutral-default", lightValue: "#80868b", darkValue: "#dadce0" },
            { name: "cm.sys.color.charts.neutral-medium", lightValue: "#dadce0", darkValue: "#9aa0a6" },
            { name: "cm.sys.color.charts.neutral-low", lightValue: "#f1f3f4", darkValue: "#47484A" },
        ]
    },
    {
        groupName: "Charts / Status",
        tokens: [
            { name: "cm.sys.color.charts.success-outline", lightValue: "#188038", darkValue: "#81c995" },
            { name: "cm.sys.color.charts.success-default", lightValue: "#188038", darkValue: "#81c995" },
            { name: "cm.sys.color.charts.success-medium", lightValue: "#81c995", darkValue: "#34a853" },
            { name: "cm.sys.color.charts.success-low", lightValue: "#ceead6", darkValue: "#314338" },
            { name: "cm.sys.color.charts.warning-outline", lightValue: "#d93025", darkValue: "#f28b82" },
            { name: "cm.sys.color.charts.warning-default", lightValue: "#f9ab00", darkValue: "#fdd663" },
            { name: "cm.sys.color.charts.warning-medium", lightValue: "#fdd663", darkValue: "#fbbc04" },
            { name: "cm.sys.color.charts.warning-low", lightValue: "#feefc3", darkValue: "#4F462C" },
            { name: "cm.sys.color.charts.error-outline", lightValue: "#d93025", darkValue: "#f28b82" },
            { name: "cm.sys.color.charts.error-default", lightValue: "#d93025", darkValue: "#f28b82" },
            { name: "cm.sys.color.charts.error-medium", lightValue: "#f28b82", darkValue: "#ea4335" },
            { name: "cm.sys.color.charts.error-low", lightValue: "#fad2cf", darkValue: "#4C3434" },
        ]
    },
    {
        groupName: "Charts / Category",
        tokens: [
            { name: "cm.sys.color.charts.category1-outline", lightValue: "#1a73e8", darkValue: "#1a73e8" },
            { name: "cm.sys.color.charts.category1-default", lightValue: "#1a73e8", darkValue: "#8ab4f8" },
            { name: "cm.sys.color.charts.category1-high", lightValue: "#185abc", darkValue: "#d2e3fc" },
            { name: "cm.sys.color.charts.category1-medium", lightValue: "#8ab4f8", darkValue: "#4285f4" },
            { name: "cm.sys.color.charts.category1-low", lightValue: "#d2e3fc", darkValue: "#333E50" },
            { name: "cm.sys.color.charts.category2-outline", lightValue: "#e52592", darkValue: "#ff8bcb" },
            { name: "cm.sys.color.charts.category2-default", lightValue: "#e52592", darkValue: "#ff8bcb" },
            { name: "cm.sys.color.charts.category2-high", lightValue: "#b80672", darkValue: "#fdcfe8" },
            { name: "cm.sys.color.charts.category2-medium", lightValue: "#ff8bcb", darkValue: "#e52592" },
            { name: "cm.sys.color.charts.category2-low", lightValue: "#fdcfe8", darkValue: "#4F3445" },
            { name: "cm.sys.color.charts.category3-outline", lightValue: "#12b5cb", darkValue: "#78d9ec" },
            { name: "cm.sys.color.charts.category3-default", lightValue: "#12b5cb", darkValue: "#78d9ec" },
            { name: "cm.sys.color.charts.category3-high", lightValue: "#098591", darkValue: "#cbf0f8" },
            { name: "cm.sys.color.charts.category3-medium", lightValue: "#78d9ec", darkValue: "#24c1e0" },
            { name: "cm.sys.color.charts.category3-low", lightValue: "#cbf0f8", darkValue: "#2F474D" },
            { name: "cm.sys.color.charts.category4-outline", lightValue: "#e8710a", darkValue: "#fcad70" },
            { name: "cm.sys.color.charts.category4-default", lightValue: "#e8710a", darkValue: "#fcad70" },
            { name: "cm.sys.color.charts.category4-high", lightValue: "#c26401", darkValue: "#fedfc8" },
            { name: "cm.sys.color.charts.category4-medium", lightValue: "#fcad70", darkValue: "#fa7b17" },
            { name: "cm.sys.color.charts.category4-low", lightValue: "#fedfc8", darkValue: "#4F3D2F" },
            { name: "cm.sys.color.charts.category5-outline", lightValue: "#9334e6", darkValue: "#c58af9" },
            { name: "cm.sys.color.charts.category5-default", lightValue: "#9334e6", darkValue: "#c58af9" },
            { name: "cm.sys.color.charts.category5-high", lightValue: "#7627bb", darkValue: "#e9d2fd" },
            { name: "cm.sys.color.charts.category5-medium", lightValue: "#c58af9", darkValue: "#af5cf7" },
            { name: "cm.sys.color.charts.category5-low", lightValue: "#e9d2fd", darkValue: "#423450" },
            { name: "cm.sys.color.charts.category6-outline", lightValue: "#d93025", darkValue: "#f28b82" },
            { name: "cm.sys.color.charts.category6-default", lightValue: "#f9ab00", darkValue: "#fdd663" },
            { name: "cm.sys.color.charts.category6-high", lightValue: "#ea8600", darkValue: "#feefc3" },
            { name: "cm.sys.color.charts.category6-medium", lightValue: "#fdd663", darkValue: "#fbbc04" },
            { name: "cm.sys.color.charts.category6-low", lightValue: "#feefc3", darkValue: "#4F462C" },
            { name: "cm.sys.color.charts.category7-outline", lightValue: "#188038", darkValue: "#81c995" },
            { name: "cm.sys.color.charts.category7-default", lightValue: "#689F38", darkValue: "#AED581" },
            { name: "cm.sys.color.charts.category7-high", lightValue: "#33691E", darkValue: "#DCEDC8" },
            { name: "cm.sys.color.charts.category7-medium", lightValue: "#AED581", darkValue: "#8BC34A" },
            { name: "cm.sys.color.charts.category7-low", lightValue: "#DCEDC8", darkValue: "#314338" },
            { name: "cm.sys.color.charts.category8-outline", lightValue: "#80868b", darkValue: "#dadce0" },
            { name: "cm.sys.color.charts.category8-default", lightValue: "#80868b", darkValue: "#dadce0" },
            { name: "cm.sys.color.charts.category8-high", lightValue: "#3c4043", darkValue: "#f1f3f4" },
            { name: "cm.sys.color.charts.category8-medium", lightValue: "#dadce0", darkValue: "#9aa0a6" },
            { name: "cm.sys.color.charts.category8-low", lightValue: "#f1f3f4", darkValue: "#47484A" },
        ]
    },
    {
        groupName: "Charts / Area",
        tokens: [
            { name: "cm.sys.color.charts.area.category1-outline", lightValue: "#1967D2", darkValue: "#8AB4F8" },
            { name: "cm.sys.color.charts.area.category1-fill", lightValue: "#d2e3fc", darkValue: "#333E50" },
            { name: "cm.sys.color.charts.area.category2-outline", lightValue: "#c92786", darkValue: "#ff8bcb" },
            { name: "cm.sys.color.charts.area.category2-fill", lightValue: "#fdcfe8", darkValue: "#4F3445" },
            { name: "cm.sys.color.charts.area.category3-outline", lightValue: "#007b83", darkValue: "#78d9ec" },
            { name: "cm.sys.color.charts.area.category3-fill", lightValue: "#cbf0f8", darkValue: "#2F474D" },
            { name: "cm.sys.color.charts.area.category4-outline", lightValue: "#E64A19", darkValue: "#FF8A65" },
            { name: "cm.sys.color.charts.area.category4-fill", lightValue: "#FFCCBC", darkValue: "#4F342D" },
            { name: "cm.sys.color.charts.area.category5-outline", lightValue: "#8430ce", darkValue: "#c58af9" },
            { name: "cm.sys.color.charts.area.category5-fill", lightValue: "#e9d2fd", darkValue: "#423450" },
            { name: "cm.sys.color.charts.area.category6-outline", lightValue: "#c5221f", darkValue: "#f28b82" },
            { name: "cm.sys.color.charts.area.category6-fill", lightValue: "#feefc3", darkValue: "#4F462C" },
            { name: "cm.sys.color.charts.area.category7-outline", lightValue: "#188038", darkValue: "#81c995" },
            { name: "cm.sys.color.charts.area.category7-fill", lightValue: "#ceead6", darkValue: "#314338" },
            { name: "cm.sys.color.charts.area.category8-outline", lightValue: "#5f6368", darkValue: "#dadce0" },
            { name: "cm.sys.color.charts.area.category8-fill", lightValue: "#f1f3f4", darkValue: "#47484A" },
        ]
    },
    {
        groupName: "Charts / Line",
        tokens: [
            { name: "cm.sys.color.charts.line.category1", lightValue: "#1a73e8", darkValue: "#8ab4f8" },
            { name: "cm.sys.color.charts.line.category2", lightValue: "#f439a0", darkValue: "#ff8bcb" },
            { name: "cm.sys.color.charts.line.category3", lightValue: "#12b5cb", darkValue: "#78d9ec" },
            { name: "cm.sys.color.charts.line.category4", lightValue: "#FF5722", darkValue: "#FF8A65" },
            { name: "cm.sys.color.charts.line.category5", lightValue: "#af5cf7", darkValue: "#c58af9" },
            { name: "cm.sys.color.charts.line.category6", lightValue: "#689F38", darkValue: "#AED581" },
            { name: "cm.sys.color.charts.line.category7", lightValue: "#3949AB", darkValue: "#7986CB" },
            { name: "cm.sys.color.charts.line.category8", lightValue: "#e37400", darkValue: "#fdd663" },
            { name: "cm.sys.color.charts.line.category9", lightValue: "#188038", darkValue: "#81c995" },
            { name: "cm.sys.color.charts.line.category10", lightValue: "#9C27B0", darkValue: "#BA68C8" },
            { name: "cm.sys.color.charts.line.category11", lightValue: "#ea4335", darkValue: "#f28b82" },
            { name: "cm.sys.color.charts.line.category12", lightValue: "#039BE5", darkValue: "#4FC3F7" },
        ]
    },
    {
        groupName: "Charts (non-series)",
        tokens: [
            { name: "cm.sys.color.charts.axis", lightValue: "#9aa0a6", darkValue: "#e8eaed" },
            { name: "cm.sys.color.charts.axis-label", lightValue: "#5F6368", darkValue: "#9AA0A6" },
            { name: "cm.sys.color.charts.legend-label", lightValue: "#5F6368", darkValue: "#9AA0A6" },
            { name: "cm.sys.color.charts.ticks", lightValue: "#9aa0a6", darkValue: "#e8eaed" },
            { name: "cm.sys.color.charts.grid", lightValue: "#dadce0", darkValue: "#5F6368" },
            { name: "cm.sys.color.charts.threshold", lightValue: "#5F6368", darkValue: "#9AA0A6" },
            { name: "cm.sys.color.charts.unfilled", lightValue: "#dadce0", darkValue: "#5F6368" },
            { name: "cm.sys.color.charts.card-surface", lightValue: "#ffffff", darkValue: "#18191B" },
            { name: "cm.sys.color.charts.title", lightValue: "#3c4043", darkValue: "#E8EAED" },
            { name: "cm.sys.color.charts.subtitle", lightValue: "#5F6368", darkValue: "#9AA0A6" },
        ]
    }
];
