import { extendedColors } from './colors-gm3-extended';
import { elevationTokens } from './elevation-gm3';

export type ThemePalette = { [cssVar: string]: string };

export interface Theme {
  key: string;
  displayName: string;
  light: ThemePalette;
  dark: ThemePalette;
}

const m3Baseline: Theme = {
  key: "m3-baseline",
  displayName: "M3 baseline",
  light: {
    "--color-primary": "#6750A4",
    "--color-on-primary": "#FFFFFF",
    "--color-primary-container": "#EADDFF",
    "--color-on-primary-container": "#21005D",
    "--color-secondary": "#625B71",
    "--color-on-secondary": "#FFFFFF",
    "--color-secondary-container": "#E8DEF8",
    "--color-on-secondary-container": "#1D192B",
    "--color-tertiary": "#7D5260",
    "--color-on-tertiary": "#FFFFFF",
    "--color-tertiary-container": "#FFD8E4",
    "--color-on-tertiary-container": "#31111D",
    "--color-error": "#B3261E",
    "--color-on-error": "#FFFFFF",
    "--color-error-container": "#F9DEDC",
    "--color-on-error-container": "#410E0B",
    "--color-background": "#FFFBFE",
    "--color-on-background": "#1C1B1F",
    "--color-surface": "#FFFBFE",
    "--color-on-surface": "#1C1B1F",
    "--color-surface-variant": "#E7E0EC",
    "--color-on-surface-variant": "#49454F",
    "--color-outline": "#79747E",
    "--color-outline-variant": "#CAC4D0",
    "--color-shadow": "#000000",
    "--color-scrim": "#000000",
    "--color-inverse-surface": "#313033",
    "--color-inverse-on-surface": "#F4EFF4",
    "--color-inverse-primary": "#D0BCFF",
    "--color-surface-tint": "#6750A4",
    "--color-surface-dim": "#DED8E1",
    "--color-surface-bright": "#FFFBFE",
    "--color-surface-container-lowest": "#FFFFFF",
    "--color-surface-container-low": "#F7F2FA",
    "--color-surface-container": "#F3EDF7",
    "--color-surface-container-high": "#EDEBF0",
    "--color-surface-container-highest": "#E6E0E9",
    "--color-purple-40": "#7437D2",
    "--color-home-prompt-1": "#400B83", // purple-20
    "--color-home-prompt-2": "#00354A", // blue-variant20
    "--color-selection-background": "#cae5ff",
    "--color-selection-text": "#000000",
    ...elevationTokens.light,
    ...extendedColors.light,
  },
  dark: {
    "--color-primary": "#D0BCFF",
    "--color-on-primary": "#381E72",
    "--color-primary-container": "#4F378B",
    "--color-on-primary-container": "#EADDFF",
    "--color-secondary": "#CCC2DC",
    "--color-on-secondary": "#332D41",
    "--color-secondary-container": "#4A4458",
    "--color-on-secondary-container": "#E8DEF8",
    "--color-tertiary": "#EFB8C8",
    "--color-on-tertiary": "#492532",
    "--color-tertiary-container": "#633B48",
    "--color-on-tertiary-container": "#FFD8E4",
    "--color-error": "#F2B8B5",
    "--color-on-error": "#601410",
    "--color-error-container": "#8C1D18",
    "--color-on-error-container": "#F9DEDC",
    "--color-background": "#1C1B1F",
    "--color-on-background": "#E6E1E5",
    "--color-surface": "#1C1B1F",
    "--color-on-surface": "#E6E1E5",
    "--color-surface-variant": "#49454F",
    "--color-on-surface-variant": "#CAC4D0",
    "--color-outline": "#938F99",
    "--color-outline-variant": "#49454F",
    "--color-shadow": "#000000",
    "--color-scrim": "#000000",
    "--color-inverse-surface": "#E6E1E5",
    "--color-inverse-on-surface": "#1C1B1F",
    "--color-inverse-primary": "#6750A4",
    "--color-surface-tint": "#D0BCFF",
    "--color-surface-dim": "#141218",
    "--color-surface-bright": "#3B383E",
    "--color-surface-container-lowest": "#0F0D13",
    "--color-surface-container-low": "#1C1B1F",
    "--color-surface-container": "#211F26",
    "--color-surface-container-high": "#2B2930",
    "--color-surface-container-highest": "#36343B",
    "--color-purple-40": "#D9BAFD",
    "--color-home-prompt-1": "#D9BAFD", // purple-80
    "--color-home-prompt-2": "#68D4FF", // blue-variant80
    "--color-selection-background": "#38587A",
    "--color-selection-text": "#ffffff",
    ...elevationTokens.dark,
    ...extendedColors.dark,
  },
};

const forestTheme: Theme = {
  key: "forest",
  displayName: "Forest",
  light: {
    "--color-primary": "#386A1F",
    "--color-on-primary": "#FFFFFF",
    "--color-primary-container": "#B7F397",
    "--color-on-primary-container": "#082100",
    "--color-secondary": "#55624C",
    "--color-on-secondary": "#FFFFFF",
    "--color-secondary-container": "#DAE7CB",
    "--color-on-secondary-container": "#131F0D",
    "--color-tertiary": "#386666",
    "--color-on-tertiary": "#FFFFFF",
    "--color-tertiary-container": "#BCECEB",
    "--color-on-tertiary-container": "#002020",
    "--color-error": "#BA1A1A",
    "--color-on-error": "#FFFFFF",
    "--color-error-container": "#FFDAD6",
    "--color-on-error-container": "#410002",
    "--color-background": "#FCFDF6",
    "--color-on-background": "#1A1C18",
    "--color-surface": "#FCFDF6",
    "--color-on-surface": "#1A1C18",
    "--color-surface-variant": "#E0E4D6",
    "--color-on-surface-variant": "#43483E",
    "--color-outline": "#74796D",
    "--color-outline-variant": "#C3C8BB",
    "--color-shadow": "#000000",
    "--color-scrim": "#000000",
    "--color-inverse-surface": "#2F312D",
    "--color-inverse-on-surface": "#F1F1EB",
    "--color-inverse-primary": "#9CD67E",
    "--color-surface-tint": "#386A1F",
    "--color-surface-dim": "#DCDFD0",
    "--color-surface-bright": "#FCFDF6",
    "--color-surface-container-lowest": "#FFFFFF",
    "--color-surface-container-low": "#F6F7F0",
    "--color-surface-container": "#F0F1EA",
    "--color-surface-container-high": "#EAEBE5",
    "--color-surface-container-highest": "#E4E5DF",
    "--color-purple-40": "#7437D2",
    "--color-home-prompt-1": "#400B83", // purple-20
    "--color-home-prompt-2": "#00354A", // blue-variant20
    "--color-selection-background": "#cae5ff",
    "--color-selection-text": "#000000",
    ...elevationTokens.light,
    ...extendedColors.light,
  },
  dark: {
    "--color-primary": "#9CD67E",
    "--color-on-primary": "#163800",
    "--color-primary-container": "#26510A",
    "--color-on-primary-container": "#B7F397",
    "--color-secondary": "#BFCBAD",
    "--color-on-secondary": "#283420",
    "--color-secondary-container": "#3E4A35",
    "--color-on-secondary-container": "#DAE7CB",
    "--color-tertiary": "#A0D0CF",
    "--color-on-tertiary": "#003737",
    "--color-tertiary-container": "#1F4E4E",
    "--color-on-tertiary-container": "#BCECEB",
    "--color-error": "#FFB4AB",
    "--color-on-error": "#690005",
    "--color-error-container": "#93000A",
    "--color-on-error-container": "#FFDAD6",
    "--color-background": "#1A1C18",
    "--color-on-background": "#E4E5DF",
    "--color-surface": "#1A1C18",
    "--color-on-surface": "#E4E5DF",
    "--color-surface-variant": "#43483E",
    "--color-on-surface-variant": "#C3C8BB",
    "--color-outline": "#8D9386",
    "--color-outline-variant": "#43483E",
    "--color-shadow": "#000000",
    "--color-scrim": "#000000",
    "--color-inverse-surface": "#E4E5DF",
    "--color-inverse-on-surface": "#1A1C18",
    "--color-inverse-primary": "#386A1F",
    "--color-surface-tint": "#9CD67E",
    "--color-surface-dim": "#12140F",
    "--color-surface-bright": "#383A35",
    "--color-surface-container-lowest": "#0D0F0A",
    "--color-surface-container-low": "#1A1C18",
    "--color-surface-container": "#1E201C",
    "--color-surface-container-high": "#282B26",
    "--color-surface-container-highest": "#333630",
    "--color-purple-40": "#D9BAFD",
    "--color-home-prompt-1": "#D9BAFD", // purple-80
    "--color-home-prompt-2": "#68D4FF", // blue-variant80
    "--color-selection-background": "#38587A",
    "--color-selection-text": "#ffffff",
    ...elevationTokens.dark,
    ...extendedColors.dark,
  },
};

const googleTheme: Theme = {
  key: "google",
  displayName: "Google",
  light: {
    "--color-primary": "#0E57D0",
    "--color-on-primary": "#FFFFFF",
    "--color-primary-container": "#D3E3FD",
    "--color-on-primary-container": "#0842A1",
    "--color-secondary": "#01639C",
    "--color-on-secondary": "#FFFFFF",
    "--color-secondary-container": "#C1E7FF",
    "--color-on-secondary-container": "#004A76",
    "--color-tertiary": "#146C2E",
    "--color-on-tertiary": "#FFFFFF",
    "--color-tertiary-container": "#C4EED1",
    "--color-on-tertiary-container": "#125223",
    "--color-error": "#B3261E",
    "--color-on-error": "#FFFFFF",
    "--color-error-container": "#F9DEDC",
    "--color-on-error-container": "#8C1D18",
    "--color-background": "#FFFFFF",
    "--color-on-background": "#1F1F1F",
    "--color-surface": "#FFFFFF",
    "--color-on-surface": "#1F1F1F",
    "--color-surface-variant": "#E0E3E1",
    "--color-on-surface-variant": "#444746",
    "--color-outline": "#747775",
    "--color-outline-variant": "#C4C7C5",
    "--color-shadow": "#000000",
    "--color-scrim": "#000000",
    "--color-inverse-surface": "#303030",
    "--color-inverse-on-surface": "#F2F2F2",
    "--color-inverse-primary": "#A9C7FB",
    "--color-surface-tint": "#6991D6",
    "--color-surface-dim": "#D4DBE4",
    "--color-surface-bright": "#FFFFFF",
    "--color-surface-container-lowest": "#FFFFFF",
    "--color-surface-container-low": "#F9FAFD",
    "--color-surface-container": "#F0F4F9",
    "--color-surface-container-high": "#E8EEF6",
    "--color-surface-container-highest": "#DDE3E9",
    "--color-primary-fixed": "#D3E3FD",
    "--color-on-primary-fixed": "#031E49",
    "--color-primary-fixed-dim": "#A9C7FB",
    "--color-on-primary-fixed-variant": "#0842A1",
    "--color-secondary-fixed": "#C1E7FF",
    "--color-on-secondary-fixed": "#011D36",
    "--color-secondary-fixed-dim": "#80CFFF",
    "--color-on-secondary-fixed-variant": "#004A76",
    "--color-tertiary-fixed": "#C4EED1",
    "--color-on-tertiary-fixed": "#052712",
    "--color-tertiary-fixed-dim": "#6DD58C",
    "--color-on-tertiary-fixed-variant": "#125223",
    "--color-purple-40": "#7437D2",
    "--color-home-prompt-1": "#400B83", // purple-20
    "--color-home-prompt-2": "#00354A", // blue-variant20
    "--color-selection-background": "#cae5ff",
    "--color-selection-text": "#000000",
    ...elevationTokens.light,
    ...extendedColors.light,
  },
  dark: {
    "--color-primary": "#A7C7FA",
    "--color-on-primary": "#072E70",
    "--color-primary-container": "#0842A1",
    "--color-on-primary-container": "#D3E3FD",
    "--color-secondary": "#80CFFF",
    "--color-on-secondary": "#003355",
    "--color-secondary-container": "#004A77",
    "--color-on-secondary-container": "#C1E7FF",
    "--color-tertiary": "#6DD58C",
    "--color-on-tertiary": "#0A3818",
    "--color-tertiary-container": "#125223",
    "--color-on-tertiary-container": "#C4EED1",
    "--color-error": "#F1B8B5",
    "--color-on-error": "#5F1410",
    "--color-error-container": "#8C1D18",
    "--color-on-error-container": "#F9DEDC",
    "--color-background": "#131314",
    "--color-on-background": "#E3E3E3",
    "--color-surface": "#131314",
    "--color-on-surface": "#E3E3E3",
    "--color-surface-variant": "#444746",
    "--color-on-surface-variant": "#C4C7C5",
    "--color-outline": "#8E918F",
    "--color-outline-variant": "#444746",
    "--color-shadow": "#000000",
    "--color-scrim": "#000000",
    "--color-inverse-surface": "#E3E3E3",
    "--color-inverse-on-surface": "#131314",
    "--color-inverse-primary": "#0E57D0",
    "--color-surface-tint": "#A7C7FA",
    "--color-surface-dim": "#131314",
    "--color-surface-bright": "#39393A",
    "--color-surface-container-lowest": "#0D0E0E",
    "--color-surface-container-low": "#1C1C1D",
    "--color-surface-container": "#202021",
    "--color-surface-container-high": "#2A2B2C",
    "--color-surface-container-highest": "#353637",
    "--color-primary-fixed": "#D3E3FD",
    "--color-on-primary-fixed": "#031E49",
    "--color-primary-fixed-dim": "#A7C7FA",
    "--color-on-primary-fixed-variant": "#072E70",
    "--color-secondary-fixed": "#C1E7FF",
    "--color-on-secondary-fixed": "#011D36",
    "--color-secondary-fixed-dim": "#80CFFF",
    "--color-on-secondary-fixed-variant": "#003355",
    "--color-tertiary-fixed": "#C4EED1",
    "--color-on-tertiary-fixed": "#052712",
    "--color-tertiary-fixed-dim": "#6DD58C",
    "--color-on-tertiary-fixed-variant": "#0A3818",
    "--color-purple-40": "#D9BAFD",
    "--color-home-prompt-1": "#D9BAFD", // purple-80
    "--color-home-prompt-2": "#68D4FF", // blue-variant80
    "--color-selection-background": "#38587A",
    "--color-selection-text": "#ffffff",
    ...elevationTokens.dark,
    ...extendedColors.dark,
  },
};

// --- Greyscale Theme ---
// A helper to convert hex to RGB
const hexToRgb = (hex: string): { r: number; g: number; b: number } | null => {
  if (!hex) return null;
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result
    ? {
        r: parseInt(result[1], 16),
        g: parseInt(result[2], 16),
        b: parseInt(result[3], 16),
      }
    : null;
};

// A helper to convert a number to a 2-digit hex string
const componentToHex = (c: number): string => {
  const hex = c.toString(16);
  return hex.length === 1 ? "0" + hex : hex;
};

// A helper to convert RGB to hex
const rgbToHex = (r: number, g: number, b: number): string => {
  return `#${componentToHex(r)}${componentToHex(g)}${componentToHex(b)}`.toUpperCase();
};

// The desaturation function using luminance
const toGreyscale = (hex: string): string => {
  const rgb = hexToRgb(hex);
  if (!rgb) return hex; // Return original if format is invalid
  const grey = Math.round(0.2126 * rgb.r + 0.7152 * rgb.g + 0.0722 * rgb.b);
  return rgbToHex(grey, grey, grey);
};

// Desaturate extended colors
const greyscaleExtendedColors = {
  light: Object.fromEntries(
    Object.entries(extendedColors.light).map(([key, value]) => [
      key,
      toGreyscale(value),
    ]),
  ) as ThemePalette,
  dark: Object.fromEntries(
    Object.entries(extendedColors.dark).map(([key, value]) => [
      key,
      toGreyscale(value),
    ]),
  ) as ThemePalette,
};

const greyscaleTheme: Theme = {
  key: "greyscale",
  displayName: "Greyscale",
  light: {
    "--color-primary": "#5B5B5B",
    "--color-on-primary": "#FFFFFF",
    "--color-primary-container": "#E5E5E5",
    "--color-on-primary-container": "#0E0E0E",
    "--color-secondary": "#5E5E5E",
    "--color-on-secondary": "#FFFFFF",
    "--color-secondary-container": "#E3E3E3",
    "--color-on-secondary-container": "#1B1B1B",
    "--color-tertiary": "#5C5C5C",
    "--color-on-tertiary": "#FFFFFF",
    "--color-tertiary-container": "#E1E1E1",
    "--color-on-tertiary-container": "#191919",
    "--color-error": "#303030",
    "--color-on-error": "#FFFFFF",
    "--color-error-container": "#E3E3E3",
    "--color-on-error-container": "#1B1B1C",
    "--color-background": "#FAFAFA",
    "--color-on-background": "#1C1C1C",
    "--color-surface": "#FAFAFA",
    "--color-on-surface": "#1C1C1C",
    "--color-surface-variant": "#E3E3E3",
    "--color-on-surface-variant": "#474747",
    "--color-outline": "#767676",
    "--color-outline-variant": "#C7C7C7",
    "--color-shadow": "#000000",
    "--color-scrim": "#000000",
    "--color-inverse-surface": "#313131",
    "--color-inverse-on-surface": "#F1F1F1",
    "--color-inverse-primary": "#C6C6C6",
    "--color-surface-tint": "#5B5B5B",
    "--color-surface-dim": "#DBDBDB",
    "--color-surface-bright": "#FAFAFA",
    "--color-surface-container-lowest": "#FFFFFF",
    "--color-surface-container-low": "#F4F4F4",
    "--color-surface-container": "#F0F0F0",
    "--color-surface-container-high": "#ECECEC",
    "--color-surface-container-highest": "#E2E2E2",
    "--color-primary-fixed": "#E3E3E3",
    "--color-on-primary-fixed": "#1C1C1C",
    "--color-primary-fixed-dim": "#C7C7C7",
    "--color-on-primary-fixed-variant": "#474747",
    "--color-secondary-fixed": "#E3E3E3",
    "--color-on-secondary-fixed": "#1C1C1C",
    "--color-secondary-fixed-dim": "#C7C7C7",
    "--color-on-secondary-fixed-variant": "#474747",
    "--color-tertiary-fixed": "#E3E3E3",
    "--color-on-tertiary-fixed": "#1C1C1C",
    "--color-tertiary-fixed-dim": "#C7C7C7",
    "--color-on-tertiary-fixed-variant": "#474747",
    "--color-purple-40": "#555555",
    "--color-home-prompt-1": "#1D1D1D",
    "--color-home-prompt-2": "#272727",
    "--color-selection-background": "#dcdcdc",
    "--color-selection-text": "#000000",
    ...elevationTokens.light,
    ...greyscaleExtendedColors.light,
  },
  dark: {
    "--color-primary": "#C6C6C6",
    "--color-on-primary": "#2B2B2B",
    "--color-primary-container": "#424242",
    "--color-on-primary-container": "#E5E5E5",
    "--color-secondary": "#C7C7C7",
    "--color-on-secondary": "#303030",
    "--color-secondary-container": "#474747",
    "--color-on-secondary-container": "#E3E3E3",
    "--color-tertiary": "#C5C5C5",
    "--color-on-tertiary": "#2F2F2F",
    "--color-tertiary-container": "#434343",
    "--color-on-tertiary-container": "#E1E1E1",
    "--color-error": "#C7C7C7",
    "--color-on-error": "#1B1B1C",
    "--color-error-container": "#474747",
    "--color-on-error-container": "#E3E3E3",
    "--color-background": "#1C1C1C",
    "--color-on-background": "#E3E3E3",
    "--color-surface": "#1C1C1C",
    "--color-on-surface": "#E3E3E3",
    "--color-surface-variant": "#474747",
    "--color-on-surface-variant": "#C7C7C7",
    "--color-outline": "#919191",
    "--color-outline-variant": "#474747",
    "--color-shadow": "#000000",
    "--color-scrim": "#000000",
    "--color-inverse-surface": "#E3E3E3",
    "--color-inverse-on-surface": "#1C1C1C",
    "--color-inverse-primary": "#5B5B5B",
    "--color-surface-tint": "#C6C6C6",
    "--color-surface-dim": "#131313",
    "--color-surface-bright": "#393939",
    "--color-surface-container-lowest": "#0E0E0E",
    "--color-surface-container-low": "#1C1C1C",
    "--color-surface-container": "#212121",
    "--color-surface-container-high": "#2A2A2A",
    "--color-surface-container-highest": "#353535",
    "--color-primary-fixed": "#E3E3E3",
    "--color-on-primary-fixed": "#1C1C1C",
    "--color-primary-fixed-dim": "#C7C7C7",
    "--color-on-primary-fixed-variant": "#474747",
    "--color-secondary-fixed": "#E3E3E3",
    "--color-on-secondary-fixed": "#1C1C1C",
    "--color-secondary-fixed-dim": "#C7C7C7",
    "--color-on-secondary-fixed-variant": "#474747",
    "--color-tertiary-fixed": "#E3E3E3",
    "--color-on-tertiary-fixed": "#1C1C1C",
    "--color-tertiary-fixed-dim": "#C7C7C7",
    "--color-on-tertiary-fixed-variant": "#474747",
    "--color-purple-40": "#C5C5C5",
    "--color-home-prompt-1": "#C5C5C5",
    "--color-home-prompt-2": "#B8B8B8",
    "--color-selection-background": "#555555",
    "--color-selection-text": "#ffffff",
    ...elevationTokens.dark,
    ...greyscaleExtendedColors.dark,
  },
};

const customTheme: Theme = {
  key: "custom",
  displayName: "Custom",
  light: {
    "--color-primary": "#6D5E0F",
    "--color-on-primary": "#FFFFFF",
    "--color-primary-container": "#F8E287",
    "--color-on-primary-container": "#534600",
    "--color-secondary": "#665E40",
    "--color-on-secondary": "#FFFFFF",
    "--color-secondary-container": "#EEE2BC",
    "--color-on-secondary-container": "#4E472A",
    "--color-tertiary": "#43664E",
    "--color-on-tertiary": "#FFFFFF",
    "--color-tertiary-container": "#C5ECCE",
    "--color-on-tertiary-container": "#2C4E38",
    "--color-error": "#BA1A1A",
    "--color-on-error": "#FFFFFF",
    "--color-error-container": "#FFDAD6",
    "--color-on-error-container": "#93000A",
    "--color-background": "#FFF9EE",
    "--color-on-background": "#1E1B13",
    "--color-surface": "#FFF9EE",
    "--color-on-surface": "#1E1B13",
    "--color-surface-variant": "#EAE2D0",
    "--color-on-surface-variant": "#4B4739",
    "--color-outline": "#7C7767",
    "--color-outline-variant": "#CDC6B4",
    "--color-shadow": "#000000",
    "--color-scrim": "#000000",
    "--color-inverse-surface": "#333027",
    "--color-inverse-on-surface": "#F7F0E2",
    "--color-inverse-primary": "#DBC66E",
    "--color-surface-tint": "#6D5E0F",
    "--color-surface-dim": "#E0D9CC",
    "--color-surface-bright": "#FFF9EE",
    "--color-surface-container-lowest": "#FFFFFF",
    "--color-surface-container-low": "#FAF3E5",
    "--color-surface-container": "#F4EDDF",
    "--color-surface-container-high": "#EEE8DA",
    "--color-surface-container-highest": "#E8E2D4",
    "--color-primary-fixed": "#F8E287",
    "--color-on-primary-fixed": "#221B00",
    "--color-primary-fixed-dim": "#DBC66E",
    "--color-on-primary-fixed-variant": "#534600",
    "--color-secondary-fixed": "#EEE2BC",
    "--color-on-secondary-fixed": "#211B04",
    "--color-secondary-fixed-dim": "#D1C6A1",
    "--color-on-secondary-fixed-variant": "#4E472A",
    "--color-tertiary-fixed": "#C5ECCE",
    "--color-on-tertiary-fixed": "#00210F",
    "--color-tertiary-fixed-dim": "#A9D0B3",
    "--color-on-tertiary-fixed-variant": "#2C4E38",
    "--color-purple-40": "#7437D2",
    "--color-home-prompt-1": "#400B83", // purple-20
    "--color-home-prompt-2": "#00354A", // blue-variant20
    "--color-selection-background": "#cae5ff",
    "--color-selection-text": "#000000",
    ...elevationTokens.light,
    ...extendedColors.light,
  },
  dark: {
    "--color-primary": "#DBC66E",
    "--color-on-primary": "#3A3000",
    "--color-primary-container": "#534600",
    "--color-on-primary-container": "#F8E287",
    "--color-secondary": "#D1C6A1",
    "--color-on-secondary": "#363016",
    "--color-secondary-container": "#4E472A",
    "--color-on-secondary-container": "#EEE2BC",
    "--color-tertiary": "#A9D0B3",
    "--color-on-tertiary": "#143723",
    "--color-tertiary-container": "#2C4E38",
    "--color-on-tertiary-container": "#C5ECCE",
    "--color-error": "#FFB4AB",
    "--color-on-error": "#690005",
    "--color-error-container": "#93000A",
    "--color-on-error-container": "#FFDAD6",
    "--color-background": "#15130B",
    "--color-on-background": "#E8E2D4",
    "--color-surface": "#15130B",
    "--color-on-surface": "#E8E2D4",
    "--color-surface-variant": "#4B4739",
    "--color-on-surface-variant": "#CDC6B4",
    "--color-outline": "#969080",
    "--color-outline-variant": "#4B4739",
    "--color-shadow": "#000000",
    "--color-scrim": "#000000",
    "--color-inverse-surface": "#E8E2D4",
    "--color-inverse-on-surface": "#333027",
    "--color-inverse-primary": "#6D5E0F",
    "--color-surface-tint": "#DBC66E",
    "--color-surface-dim": "#15130B",
    "--color-surface-bright": "#3C3930",
    "--color-surface-container-lowest": "#100E07",
    "--color-surface-container-low": "#1E1B13",
    "--color-surface-container": "#222017",
    "--color-surface-container-high": "#2D2A21",
    "--color-surface-container-highest": "#38352B",
    "--color-primary-fixed": "#F8E287",
    "--color-on-primary-fixed": "#221B00",
    "--color-primary-fixed-dim": "#DBC66E",
    "--color-on-primary-fixed-variant": "#534600",
    "--color-secondary-fixed": "#EEE2BC",
    "--color-on-secondary-fixed": "#211B04",
    "--color-secondary-fixed-dim": "#D1C6A1",
    "--color-on-secondary-fixed-variant": "#4E472A",
    "--color-tertiary-fixed": "#C5ECCE",
    "--color-on-tertiary-fixed": "#00210F",
    "--color-tertiary-fixed-dim": "#A9D0B3",
    "--color-on-tertiary-fixed-variant": "#2C4E38",
    "--color-purple-40": "#D9BAFD",
    "--color-home-prompt-1": "#D9BAFD", // purple-80
    "--color-home-prompt-2": "#68D4FF", // blue-variant80
    "--color-selection-background": "#38587A",
    "--color-selection-text": "#ffffff",
    ...elevationTokens.dark,
    ...extendedColors.dark,
  },
};

export const themes: { [key: string]: Theme } = {
  google: googleTheme,
  "m3-baseline": m3Baseline,
  forest: forestTheme,
  greyscale: greyscaleTheme,
  custom: customTheme,
};
