import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './src/creatives/**/*.{js,ts,jsx,tsx,mdx}',
     './src/creatives/**/**/*.{js,ts,jsx,tsx,mdx}',
    './packages/design-vibe/gm3-react-components/src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      screens: {
        bp800: "800px",
      },
      borderRadius: {
        "extra-small": "0.25rem", // 4px
        small: "0.5rem", // 8px
        medium: "0.75rem", // 12px
        large: "1rem", // 16px
        "extra-large": "1.75rem", // 28px
      },
      fontFamily: {
        sans: ['Google Sans', 'Inter', 'sans-serif'],
        'google-sans': ['Google Sans', 'sans-serif'],
        'google-sans-text': ['"Google Sans Text"', 'sans-serif'],
        'google-code': ['"Google Sans Mono"', 'Menlo', 'Monaco', 'monospace'],
        'google-flex': ['"Google Sans Flex"', 'sans-serif'],
        mono: ['Google Sans Mono', 'Source Code Pro', 'monospace'],
      },
      transitionTimingFunction: {
        standard: "cubic-bezier(0.2, 0.0, 0, 1.0)",
        "standard-accelerate": "cubic-bezier(0.3, 0.0, 1, 1)",
        "standard-decelerate": "cubic-bezier(0, 0, 0, 1)",
        emphasized: "cubic-bezier(0.2, 0.0, 0, 1.0)",
        "emphasized-accelerate": "cubic-bezier(0.3, 0.0, 0.8, 0.15)",
        "emphasized-decelerate": "cubic-bezier(0.05, 0.7, 0.1, 1.0)",
        "emphasized-spring-decelerate": "cubic-bezier(0.34, 1.56, 0.64, 1)",
        "emphasized-spring-accelerate": "cubic-bezier(0.68, -0.55, 0.26, 1.55)",
        "standard-spring-decelerate": "cubic-bezier(0.18, 0.89, 0.32, 1.28)",
        "standard-spring-accelerate": "cubic-bezier(0.6, -0.28, 0.735, 0.045)",
      },
      transitionDuration: {
        short1: "50ms",
        short2: "100ms",
        short3: "150ms",
        short4: "200ms",
        medium1: "250ms",
        medium2: "300ms",
        medium3: "350ms",
        medium4: "400ms",
        long1: "450ms",
        long2: "500ms",
        long3: "550ms",
        long4: "600ms",
        "extra-long1": "700ms",
        "extra-long2": "800ms",
        "extra-long3": "900ms",
        "extra-long4": "1000ms",
      },
      boxShadow: {
        "elevation-1": "var(--shadow-elevation-1)",
        "elevation-2": "var(--shadow-elevation-2)",
        "elevation-3": "var(--shadow-elevation-3)",
        "elevation-4": "var(--shadow-elevation-4)",
        "elevation-5": "var(--shadow-elevation-5)",
      },
      colors: {
        primary: "var(--color-primary)",
        "on-primary": "var(--color-on-primary)",
        "primary-container": "var(--color-primary-container)",
        "on-primary-container": "var(--color-on-primary-container)",
        secondary: "var(--color-secondary)",
        "on-secondary": "var(--color-on-secondary)",
        "secondary-container": "var(--color-secondary-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        tertiary: "var(--color-tertiary)",
        "on-tertiary": "var(--color-on-tertiary)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        error: "var(--color-error)",
        "on-error": "var(--color-on-error)",
        "error-container": "var(--color-error-container)",
        "on-error-container": "var(--color-on-error-container)",
        background: "var(--color-background)",
        "on-background": "var(--color-on-background)",
        surface: "var(--color-surface)",
        "on-surface": "var(--color-on-surface)",
        "surface-variant": "var(--color-surface-variant)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        outline: "var(--color-outline)",
        "outline-variant": "var(--color-outline-variant)",
        shadow: "var(--color-shadow)",
        scrim: "var(--color-scrim)",
        "inverse-surface": "var(--color-inverse-surface)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "inverse-primary": "var(--color-inverse-primary)",
        "surface-tint": "var(--color-surface-tint)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",

        /* Opacity-based tokens using RGB variants */
        "on-surface-8": "rgba(var(--color-on-surface-rgb), 0.08)",
        "on-surface-10": "rgba(var(--color-on-surface-rgb), 0.10)",
        "on-surface-12": "rgba(var(--color-on-surface-rgb), 0.12)",
        "on-surface-16": "rgba(var(--color-on-surface-rgb), 0.16)",
        "on-surface-38": "rgba(var(--color-on-surface-rgb), 0.38)",
        "primary-8": "rgba(var(--color-primary-rgb), 0.08)",
        "primary-10": "rgba(var(--color-primary-rgb), 0.10)",
        "primary-16": "rgba(var(--color-primary-rgb), 0.16)",
        "secondary-8": "rgba(var(--color-secondary-rgb), 0.08)",
        "secondary-10": "rgba(var(--color-secondary-rgb), 0.10)",
        "secondary-16": "rgba(var(--color-secondary-rgb), 0.16)",
      },
    },
  },
  plugins: [],
} satisfies Config;